env:
  es2021: true
extends:
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - simple-import-sort
rules:
  "simple-import-sort/imports": "error"
  jsx-quotes: ["error", "prefer-single"]
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
ignorePatterns:
  - "*.d.ts"
  - "*.min.js"
  - "build/*"
